### ISSUE TITLE
[RFC] Switch @glimmer/syntax with handlebars

### ISSUE THREAD

**Issue by AndrewLeedham** [danakt/handlebars-to-jsx#10]
After having a conversation with some of the `@glimmer/syntax` maintainers (https://github.com/glimmerjs/glimmer-vm/issues/948), it seems they do not support partials in any form, and the module is specific to Ember's handlebars flavour. Therefore in order to support #3, and to move away from the Ember specific stuff, I think it would make sense to convert this module to use https://github.com/wycats/handlebars.js which provides a `.parse` function to generate an AST. @danakt is this something you considered when writing the module, and do you have any reservations?

**Comment by danakt** [comment]
Originally I wanted to use [handlebars](https://github.com/wycats/handlebars.js) parser. But, unfortunately, it works with templates as with plain text, and doesn't build HTML AST, this means that it is suitable for any syntax, but this makes it unsuitable for the task of parsing HTML code. Meanwhile, the [glimmer](https://github.com/glimmerjs/glimmer-vm) parser builds HTML AST, which can be fully translated.

You can see how it looks in [astexplorer.net](https://astexplorer.net/), there are both parsers.

**Comment by Rykus0** [comment]
Another limitation to note is that it only allows blocks in other blocks or html tags.  Meaning you cannot use blocks to conditionally set attributes, which I'm finding to be particularly limiting.
