### ISSUE TITLE
Module not found: Error: Can't resolve './program' in 

### ISSUE THREAD

**Issue by ghost** [danakt/handlebars-to-jsx#20]
Hi,

I think the published package is not built correctly. Here is the error I'm facing when I tried to use the tool.

![image](https://user-images.githubusercontent.com/6542274/88932739-1bb80f80-d29c-11ea-9a07-881fbcc9a38c.png)

Thanks,
Vetri

**Comment by ghost** [comment]
I resolved the issue,

Here is what I did.

`
npm i &&
npm run build
`

**Comment by fnaquira** [comment]
Where did you do this? I did it on the folder module but still got errors...
Is there a way to solved on the main repository?

**Comment by ghost** [comment]
@fnaquira  can you try  ```cd handlebars-to-jsx && npm i && npm run build```

**Comment by Rykus0** [comment]
I was able to resolve this _temporarily_ by running build, as described. (noting that it is the subfolder under `node_modules`).  I wanted to point out that the issue itself is not resolved, though.

**Comment by salomvary** [comment]
I have rebuilt and republished the package under `@salomvary/handlebars-to-jsx`.

Also added a command line utility: https://github.com/salomvary/handlebars-to-jsx#command-line-usage

**Comment by danakt** [comment]
Thank you! Fixed in 0.1.4
